#!/usr/bin/env python3
"""SEO tags for the Castros Consultoria site, from one source of truth (tools/seo.json).

Run from anywhere (paths are relative to the repo root, the folder above tools/):
    python3 tools/seo.py           write the SEO block in every page's <head>, the EN tab titles in
                                   js/translations.json and, once site_url is set, sitemap.xml + robots.txt
    python3 tools/seo.py --check   change nothing; exit 1 if a page is out of date or a rule is broken

Why a script and static tags (not JavaScript): WhatsApp, Facebook and LinkedIn read the raw HTML and do not
run JavaScript, and every absolute URL (canonical, og:url, og:image, sitemap) depends on the domain, which
should be one setting in seo.json, not dozens of hand edits.

What the block holds (between <!-- SEO:START ... --> and <!-- SEO:END -->, which the script owns):
  title (+ data-i18n so the tab follows the PT/EN switch), meta description, favicon links, Open Graph,
  and JSON-LD business data on pages with "business_data": true.
  With site_url set it adds: canonical, og:url, og:image (+ size, alt), twitter:card, and the WebSite data.
Standard library only (Python 3.8+).
"""
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = ROOT / "tools" / "seo.json"
TRANSLATIONS = ROOT / "js" / "translations.json"
START = "<!-- SEO:START · generated by tools/seo.py from tools/seo.json — edit those, not this block -->"
END = "<!-- SEO:END -->"
BLOCK_RE = re.compile(r"^([ \t]*)<!-- SEO:START\b.*?<!-- SEO:END -->[ \t]*\n", re.S | re.M)
TITLE_RE = re.compile(r"^([ \t]*)<title\b[^>]*>.*?</title>[ \t]*\n", re.S | re.M)
TITLE_LEN = (30, 60)
DESC_LEN = (70, 160)


def attr(value):
    return html.escape(value, quote=True)


def absolute(site_url, path):
    return site_url + "/" + path.lstrip("/")


def rel(page_file, asset):
    """asset path relative to the page (pages in html/ need ../)"""
    depth = page_file.count("/")
    return "../" * depth + asset


def business_jsonld(cfg, page):
    b, site = cfg["business"], cfg["site_url"]
    org = {
        "@type": b["type"],
        "name": b["name"],
        "alternateName": b["alternate_name"],
        "description": page["description"],
        "address": {"@type": "PostalAddress", "addressLocality": b["locality"], "addressCountry": b["country"]},
        "openingHoursSpecification": [{
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": b["hours"]["days"],
            "opens": b["hours"]["opens"],
            "closes": b["hours"]["closes"],
        }],
    }
    if b.get("telephone"):
        org["telephone"] = b["telephone"]
    if b.get("email"):
        org["email"] = b["email"]
    if b.get("same_as"):
        org["sameAs"] = b["same_as"]
    graph = [org]
    if site:
        org["@id"] = absolute(site, "/#business")
        org["url"] = absolute(site, "/")
        org["logo"] = absolute(site, b["logo"])
        org["image"] = absolute(site, cfg["share_image"]["path"])
        graph.append({
            "@type": "WebSite",
            "@id": absolute(site, "/#website"),
            "name": b["name"],
            "alternateName": b["alternate_name"],
            "url": absolute(site, "/"),
            "inLanguage": "pt-MZ",
            "publisher": {"@id": absolute(site, "/#business")},
        })
    data = {"@context": "https://schema.org", "@graph": graph} if len(graph) > 1 else {"@context": "https://schema.org", **org}
    return json.dumps(data, ensure_ascii=False, indent=2).replace("</", "<\\/")


def build_block(cfg, page, indent):
    site, f = cfg["site_url"], page["file"]
    icons, img = cfg["icons"], cfg["share_image"]
    lines = [
        START,
        f'<title data-i18n="meta.{page["key"]}.title">{html.escape(page["title"]["pt"], quote=False)}</title>',
        f'<meta name="description" content="{attr(page["description"])}">',
    ]
    if site:
        lines.append(f'<link rel="canonical" href="{attr(absolute(site, page["url_path"]))}">')
    lines += [
        f'<link rel="icon" href="{rel(f, icons["ico"])}" sizes="48x48">',
        f'<link rel="icon" href="{rel(f, icons["png192"])}" type="image/png" sizes="192x192">',
        f'<link rel="apple-touch-icon" href="{rel(f, icons["apple"])}">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{attr(cfg["business"]["name"])}">',
        f'<meta property="og:locale" content="{attr(cfg["locale"])}">',
        f'<meta property="og:title" content="{attr(page["title"]["pt"])}">',
        f'<meta property="og:description" content="{attr(page["description"])}">',
    ]
    if site:
        lines += [
            f'<meta property="og:url" content="{attr(absolute(site, page["url_path"]))}">',
            f'<meta property="og:image" content="{attr(absolute(site, img["path"]))}">',
            f'<meta property="og:image:width" content="{img["width"]}">',
            f'<meta property="og:image:height" content="{img["height"]}">',
            f'<meta property="og:image:alt" content="{attr(img["alt"])}">',
            '<meta name="twitter:card" content="summary_large_image">',
        ]
    if page.get("business_data"):
        lines.append('<script type="application/ld+json">')
        lines += ["  " + l for l in business_jsonld(cfg, page).split("\n")]
        lines.append("</script>")
    lines.append(END)
    return "".join(indent + l + "\n" for l in lines)


def render_page(cfg, page, text):
    """return the page text with an up-to-date SEO block (first run: the block replaces the old <title>)"""
    m = BLOCK_RE.search(text)
    if m:
        indent = m.group(1)
        return text[:m.start()] + build_block(cfg, page, indent) + text[m.end():]
    titles = list(TITLE_RE.finditer(text))
    if len(titles) != 1:
        raise SystemExit(f"{page['file']}: expected one <title> to replace, found {len(titles)}")
    t = titles[0]
    return text[:t.start()] + build_block(cfg, page, t.group(1)) + text[t.end():]


def render_translations(cfg, raw):
    """EN tab titles (+ the PT reference copy) under meta.<key>.title; old meta.* keys are dropped"""
    data = json.loads(raw)
    for lang in ("pt", "en"):
        new_meta = {f'meta.{p["key"]}.title': p["title"][lang] for p in cfg["pages"]}
        out, placed = {}, False
        for k, v in data[lang].items():
            if k.startswith("meta."):
                if not placed:
                    out.update(new_meta)
                    placed = True
                continue
            out[k] = v
        if not placed:
            out = {**new_meta, **out}
        data[lang] = out
    return json.dumps(data, indent=2, ensure_ascii=False)


def render_sitemap(cfg):
    urls = "".join(f"  <url><loc>{html.escape(absolute(cfg['site_url'], p['url_path']))}</loc></url>\n"
                   for p in cfg["pages"])
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls + "</urlset>\n")


def render_robots(cfg):
    return f"User-agent: *\nAllow: /\n\nSitemap: {absolute(cfg['site_url'], '/sitemap.xml')}\n"


def rule_errors(cfg):
    errs = []
    site = cfg["site_url"]
    if site and (not site.startswith("https://") or site.endswith("/")):
        errs.append("site_url must start with https:// and have no trailing slash")
    seen_t, seen_d = {}, {}
    for p in cfg["pages"]:
        for lang in ("pt", "en"):
            t = p["title"][lang]
            if not TITLE_LEN[0] <= len(t) <= TITLE_LEN[1]:
                errs.append(f"{p['file']}: title.{lang} is {len(t)} characters (allowed {TITLE_LEN[0]}-{TITLE_LEN[1]})")
        d = p["description"]
        if not DESC_LEN[0] <= len(d) <= DESC_LEN[1]:
            errs.append(f"{p['file']}: description is {len(d)} characters (allowed {DESC_LEN[0]}-{DESC_LEN[1]})")
        if p["title"]["pt"] in seen_t:
            errs.append(f"{p['file']}: same title as {seen_t[p['title']['pt']]}")
        if d in seen_d:
            errs.append(f"{p['file']}: same description as {seen_d[d]}")
        seen_t[p["title"]["pt"]], seen_d[d] = p["file"], p["file"]
        if not (ROOT / p["file"]).exists():
            errs.append(f"{p['file']}: page not found")
    for asset in [cfg["share_image"]["path"], cfg["business"]["logo"], *cfg["icons"].values()]:
        if not (ROOT / asset).exists():
            errs.append(f"{asset}: file not found")
    return errs


def main():
    check = "--check" in sys.argv[1:]
    cfg = json.loads(CONFIG.read_text(encoding="utf-8"))
    errs = rule_errors(cfg)
    if errs:
        print("\n".join("rule: " + e for e in errs))
        sys.exit(1)

    wanted = {}
    for p in cfg["pages"]:
        path = ROOT / p["file"]
        text = path.read_text(encoding="utf-8")
        new = render_page(cfg, p, text)
        if len(re.findall(r"<title\b", new)) != 1 or len(re.findall(r'<meta name="description"', new)) != 1:
            sys.exit(f"{p['file']}: a <title> or meta description exists outside the SEO block; remove it")
        wanted[path] = (text, new)
    raw = TRANSLATIONS.read_text(encoding="utf-8")
    wanted[TRANSLATIONS] = (raw, render_translations(cfg, raw))
    for name, render in (("sitemap.xml", render_sitemap), ("robots.txt", render_robots)):
        path = ROOT / name
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if cfg["site_url"]:
            wanted[path] = (old, render(cfg))
        elif old is not None:
            print(f"note: {name} exists but site_url is empty; it was written for a domain that is no longer set")

    stale = [p for p, (old, new) in wanted.items() if old != new]
    if check:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)}  (run python3 tools/seo.py)")
        print("seo check: OK" if not stale else f"seo check: {len(stale)} file(s) out of date")
        sys.exit(1 if stale else 0)
    for p in stale:
        p.write_text(wanted[p][1], encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    if not stale:
        print("nothing to change")


if __name__ == "__main__":
    main()
